version: "3.8"
services:
  postgres:
    image: postgres:16.3
    container_name: eatgo-db
    restart: always
    environment:
      POSTGRES_USER: eatgo_user
      POSTGRES_PASSWORD: eatgo_pass
      POSTGRES_DB: eatgo
    ports:
      - "5432:5432"
    volumes:
      - eatgo_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: eatgo-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.pl
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  eatgo_data:
  pgadmin_data:
